repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        exclude: ^tests/res/
        args: [--safe]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: ^tests/res/
        additional_dependencies:
            - flake8-bugbear==22.8.23
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        exclude: ^tests/res/
        args: [--strict, --ignore-missing-imports, --disable-error-code=unused-ignore]
        additional_dependencies:
            - libcst==1.4.0
            - docstring_parser>=0.16
            - pytest>=6.0