name: Tests

on:
  - push

jobs:
  test:

    # Note: if we were actually testing on different environments, we would need to move
    # the linting to a separate job/workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: flake8
      run: tox -e flake8
    - name: Black
      run: tox -e black
    - name: MyPy
      run: tox -e mypy
    - name: PyTest
      run: tox -e py312
    - name: Codecov Badge
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
      token: ${{ secrets.CODECOV_TOKEN }}
      verbose: true # optional (default = false)
